/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Contractors.Constractor;
import DB.Confix;
import DB.ConstractorDB;
import Empty.Client;
import Empty.OrderService;
import Empty.Orders;
import Empty.Room;
import Empty.Staff;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Hotel extends javax.swing.JFrame {

    private int max;
    private int bc = 8;
    private Constractor constractor;
    private DefaultTableModel TbModel;

    /**
     * Creates new form Main
     */
    public Hotel() {
        initComponents();
        constractor = new Constractor();
        consDB = new ConstractorDB();
//        TableContent(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConnectoDB_dialog = new javax.swing.JDialog();
        Conec_bt = new javax.swing.JButton();
        ClearDb_bt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IpAdress_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        port_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Services_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        userNamedb_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        passDb_tf = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        CloseDB_bt = new javax.swing.JButton();
        Staff_InternarFrame = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idStaff_tf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        staffname_tf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        StaffMale_btradio = new javax.swing.JRadioButton();
        staffFemale_btradio = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        Staff_phone_tf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        staff_mail_tf = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        staff_office_tf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Staff_table = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        staff_add_bt = new javax.swing.JButton();
        staff_Reset_bt = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        staff_search_tf = new javax.swing.JTextField();
        staff_search_bt = new javax.swing.JButton();
        staffGender = new javax.swing.ButtonGroup();
        Order_InternerFrame = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Order_list = new javax.swing.JList();
        Checkin_Panel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        CheckIn_NameClient = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Checkin_AgeClient = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Ckeckin_Client_Phone_tf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Checkin_Client_Datein_tf = new javax.swing.JTextField();
        Checkin_Address_Client_tf = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Checkin_Client_dateout_tf = new javax.swing.JTextField();
        Checkin_Female_Client_rd = new javax.swing.JRadioButton();
        Checkin_Male_Client_rd = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        Ckeckin_Client_CMND_tf = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Checkin_Room_Table = new javax.swing.JTable();
        CheckIn_insert_bt = new javax.swing.JButton();
        Ckeckin_Update_bt = new javax.swing.JButton();
        Checkin_Clear_bt = new javax.swing.JButton();
        Checkin_Client_Gender_btgroup = new javax.swing.ButtonGroup();
        Order_Question_dialog = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        Question_Yes_bt = new javax.swing.JButton();
        Question_No_bt = new javax.swing.JButton();
        CheckOut = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        staff_bt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Ordel_bt = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        MainFrame = new javax.swing.JDesktopPane();
        LoginFrame = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        Account_tf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        LoginBt = new javax.swing.JButton();
        ResetBt = new javax.swing.JButton();
        loginStatus = new javax.swing.JLabel();
        PassWord = new javax.swing.JPasswordField();
        Wellcome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        StatusTxt = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        ConnectoDB_dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        ConnectoDB_dialog.setMinimumSize(new java.awt.Dimension(410, 320));
        ConnectoDB_dialog.setSize(new java.awt.Dimension(300, 250));

        Conec_bt.setText("Connec");
        Conec_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conec_btActionPerformed(evt);
            }
        });

        ClearDb_bt.setText("Clear");
        ClearDb_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearDb_btActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText(" Databases Information");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ip address :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Port :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Name DB :");

        Services_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Services_tfActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("User Name :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Pass :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IpAdress_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(port_tf)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(15, 15, 15)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passDb_tf)
                            .addComponent(userNamedb_tf, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Services_tf))))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {IpAdress_tf, Services_tf, port_tf});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IpAdress_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(port_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Services_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNamedb_tf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(passDb_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {IpAdress_tf, Services_tf, passDb_tf, port_tf, userNamedb_tf});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel6, jLabel7, jLabel8, jLabel9});

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/db.jpg"))); // NOI18N

        CloseDB_bt.setText("Close");
        CloseDB_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseDB_btActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConnectoDB_dialogLayout = new javax.swing.GroupLayout(ConnectoDB_dialog.getContentPane());
        ConnectoDB_dialog.getContentPane().setLayout(ConnectoDB_dialogLayout);
        ConnectoDB_dialogLayout.setHorizontalGroup(
            ConnectoDB_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(ConnectoDB_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConnectoDB_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConnectoDB_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ConnectoDB_dialogLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConnectoDB_dialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(Conec_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearDb_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(CloseDB_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ConnectoDB_dialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ClearDb_bt, CloseDB_bt, Conec_bt});

        ConnectoDB_dialogLayout.setVerticalGroup(
            ConnectoDB_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectoDB_dialogLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConnectoDB_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConnectoDB_dialogLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ConnectoDB_dialogLayout.createSequentialGroup()
                        .addGroup(ConnectoDB_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Conec_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearDb_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CloseDB_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        ConnectoDB_dialogLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ClearDb_bt, CloseDB_bt, Conec_bt});

        Staff_InternarFrame.setClosable(true);
        Staff_InternarFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Staff_InternarFrame.setTitle("Staff Manager");
        Staff_InternarFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/staff.png"))); // NOI18N
        Staff_InternarFrame.setPreferredSize(new java.awt.Dimension(800, 600));
        Staff_InternarFrame.setVisible(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(223, 342));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Add/Update");

        jLabel12.setText("StaffID :");

        jLabel13.setText("Name :");

        jLabel14.setText("Gender :");

        StaffMale_btradio.setText("Male");

        staffFemale_btradio.setText("Female");

        jLabel15.setText("Phone number :");

        jLabel16.setText("Email :");

        jLabel17.setText("Office :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(StaffMale_btradio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(staffFemale_btradio))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel15)))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(staff_office_tf)
                            .addComponent(staff_mail_tf)
                            .addComponent(idStaff_tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(staffname_tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Staff_phone_tf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idStaff_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffMale_btradio)
                    .addComponent(staffFemale_btradio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Staff_phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staff_mail_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(staff_office_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 402));

        Staff_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Staff_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Staff_table);

        staff_add_bt.setText("Add");
        staff_add_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_add_btActionPerformed(evt);
            }
        });

        staff_Reset_bt.setText("Reset");
        staff_Reset_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_Reset_btActionPerformed(evt);
            }
        });

        jButton12.setText("Delete");

        staff_search_tf.setText("Search By Name");

        staff_search_bt.setText("Search");

        javax.swing.GroupLayout Staff_InternarFrameLayout = new javax.swing.GroupLayout(Staff_InternarFrame.getContentPane());
        Staff_InternarFrame.getContentPane().setLayout(Staff_InternarFrameLayout);
        Staff_InternarFrameLayout.setHorizontalGroup(
            Staff_InternarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_InternarFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Staff_InternarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Staff_InternarFrameLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(Staff_InternarFrameLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(staff_add_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(staff_Reset_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(staff_search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(staff_search_bt)
                .addGap(11, 11, 11))
        );

        Staff_InternarFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton12, staff_Reset_bt, staff_add_bt, staff_search_bt});

        Staff_InternarFrameLayout.setVerticalGroup(
            Staff_InternarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_InternarFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Staff_InternarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Staff_InternarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staff_Reset_bt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Staff_InternarFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(staff_add_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(staff_search_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(staff_search_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Staff_InternarFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton12, staff_Reset_bt, staff_add_bt, staff_search_bt});

        Order_InternerFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        Order_InternerFrame.setTitle("Order Mananger");
        Order_InternerFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order2.png"))); // NOI18N
        Order_InternerFrame.setMinimumSize(new java.awt.Dimension(87, 34));
        Order_InternerFrame.setNormalBounds(new java.awt.Rectangle(0, 0, 87, 0));
        Order_InternerFrame.setPreferredSize(new java.awt.Dimension(800, 600));
        Order_InternerFrame.setVisible(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Order_list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Check In", "Check Out", "Order Services", "Information Cliet", "Change Room", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        Order_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Order_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Order_list);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        Checkin_Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Checkin_Panel.setMinimumSize(new java.awt.Dimension(0, 0));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Check In :");

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Information Client :");

        jLabel20.setText("Name :");

        jLabel21.setText("Age :");

        Checkin_AgeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkin_AgeClientActionPerformed(evt);
            }
        });

        jLabel22.setText("Gender :");

        jLabel23.setText("Address :");

        jLabel24.setText("Phone number :");

        jLabel25.setText("Date In :");

        jLabel26.setText("Date Out :");

        Checkin_Client_Gender_btgroup.add(Checkin_Female_Client_rd);
        Checkin_Female_Client_rd.setText("Female");

        Checkin_Client_Gender_btgroup.add(Checkin_Male_Client_rd);
        Checkin_Male_Client_rd.setText("Male");

        jLabel27.setText("CMND :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CheckIn_NameClient)
                                    .addComponent(Checkin_AgeClient)
                                    .addComponent(Checkin_Address_Client_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(Checkin_Female_Client_rd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(Checkin_Male_Client_rd)))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel26)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ckeckin_Client_Phone_tf)
                            .addComponent(Checkin_Client_Datein_tf)
                            .addComponent(Checkin_Client_dateout_tf)
                            .addComponent(Ckeckin_Client_CMND_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckIn_NameClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ckeckin_Client_Phone_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Checkin_AgeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Checkin_Client_Datein_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Checkin_Female_Client_rd)
                        .addComponent(Checkin_Male_Client_rd))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Checkin_Client_dateout_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Checkin_Address_Client_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ckeckin_Client_CMND_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Checkin_Room_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Checkin_Room_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Checkin_Room_TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Checkin_Room_Table);

        CheckIn_insert_bt.setText("Insert");
        CheckIn_insert_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckIn_insert_btActionPerformed(evt);
            }
        });

        Ckeckin_Update_bt.setText("Update");

        Checkin_Clear_bt.setText("Clear");

        javax.swing.GroupLayout Checkin_PanelLayout = new javax.swing.GroupLayout(Checkin_Panel);
        Checkin_Panel.setLayout(Checkin_PanelLayout);
        Checkin_PanelLayout.setHorizontalGroup(
            Checkin_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Checkin_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Checkin_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Checkin_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(512, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Checkin_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CheckIn_insert_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ckeckin_Update_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Checkin_Clear_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Checkin_PanelLayout.setVerticalGroup(
            Checkin_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Checkin_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Checkin_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckIn_insert_bt)
                    .addComponent(Ckeckin_Update_bt)
                    .addComponent(Checkin_Clear_bt))
                .addContainerGap())
        );

        javax.swing.GroupLayout Order_InternerFrameLayout = new javax.swing.GroupLayout(Order_InternerFrame.getContentPane());
        Order_InternerFrame.getContentPane().setLayout(Order_InternerFrameLayout);
        Order_InternerFrameLayout.setHorizontalGroup(
            Order_InternerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Order_InternerFrameLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Checkin_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Order_InternerFrameLayout.setVerticalGroup(
            Order_InternerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Order_InternerFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Order_InternerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkin_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Order_Question_dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Order_Question_dialog.setTitle("Question Order");
        Order_Question_dialog.setLocation(new java.awt.Point(200, 330));
        Order_Question_dialog.setSize(new java.awt.Dimension(345, 150));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Do you want insert (Y/N)");

        Question_Yes_bt.setText("Yes");
        Question_Yes_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question_Yes_btActionPerformed(evt);
            }
        });

        Question_No_bt.setText("No");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(Question_Yes_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Question_No_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Question_Yes_bt)
                    .addComponent(Question_No_bt))
                .addContainerGap())
        );

        javax.swing.GroupLayout Order_Question_dialogLayout = new javax.swing.GroupLayout(Order_Question_dialog.getContentPane());
        Order_Question_dialog.getContentPane().setLayout(Order_Question_dialogLayout);
        Order_Question_dialogLayout.setHorizontalGroup(
            Order_Question_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Order_Question_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Order_Question_dialogLayout.setVerticalGroup(
            Order_Question_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Order_Question_dialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CheckOutLayout = new javax.swing.GroupLayout(CheckOut);
        CheckOut.setLayout(CheckOutLayout);
        CheckOutLayout.setHorizontalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        CheckOutLayout.setVerticalGroup(
            CheckOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project Manager Hotel of Students Aptech FPT University");
        setBackground(new java.awt.Color(51, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(200, 20));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 60));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 60));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 60));
        jPanel1.setRequestFocusEnabled(false);

        staff_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/staff.png"))); // NOI18N
        staff_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_btActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Rooms.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Services.jpg"))); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Account.png"))); // NOI18N

        Ordel_bt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/order2.png"))); // NOI18N
        Ordel_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ordel_btActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/summary.png"))); // NOI18N

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/imageAdmin.png"))); // NOI18N
        jButton6.setText("Admin");

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/changePass.png"))); // NOI18N
        jButton7.setText("Change PassWord");

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recycle bin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staff_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ordel_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Ordel_bt, jButton1, jButton2, jButton3, jButton5, jButton9, staff_bt});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(staff_bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ordel_bt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        MainFrame.setBackground(new java.awt.Color(153, 153, 255));

        LoginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        LoginFrame.setTitle("Login");
        LoginFrame.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Lock.png"))); // NOI18N
        LoginFrame.setVisible(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("User Name :");

        Account_tf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Account_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Account_tfKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Pass Word :");

        LoginBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Key (2).png"))); // NOI18N
        LoginBt.setText("Login");
        LoginBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtActionPerformed(evt);
            }
        });

        ResetBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Reset.png"))); // NOI18N
        ResetBt.setText("Reset");

        loginStatus.setForeground(new java.awt.Color(255, 51, 51));

        PassWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PassWordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout LoginFrameLayout = new javax.swing.GroupLayout(LoginFrame.getContentPane());
        LoginFrame.getContentPane().setLayout(LoginFrameLayout);
        LoginFrameLayout.setHorizontalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Account_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PassWord)))
                    .addGroup(LoginFrameLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(LoginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(ResetBt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        LoginFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {LoginBt, ResetBt});

        LoginFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        LoginFrameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Account_tf, PassWord});

        LoginFrameLayout.setVerticalGroup(
            LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginFrameLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Account_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResetBt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(LoginBt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );

        LoginFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {LoginBt, ResetBt});

        LoginFrameLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        MainFrame.add(LoginFrame);
        LoginFrame.setBounds(300, 160, 360, 230);

        Wellcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo.png"))); // NOI18N
        Wellcome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MainFrame.add(Wellcome);
        Wellcome.setBounds(130, 80, 700, 360);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(653, 35));

        StatusTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        StatusTxt.setText(" Login Please !");
        StatusTxt.setMaximumSize(new java.awt.Dimension(75, 15));
        StatusTxt.setMinimumSize(new java.awt.Dimension(75, 15));
        StatusTxt.setPreferredSize(new java.awt.Dimension(75, 15));

        jLabel4.setText("Copyright @ 2016");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(StatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu.setMaximumSize(new java.awt.Dimension(60, 32769));
        Menu.setPreferredSize(new java.awt.Dimension(60, 21));

        jMenu1.setText("File");
        Menu.add(jMenu1);

        jMenu2.setText("Edit");
        Menu.add(jMenu2);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
            .addComponent(MainFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// chinh dong chay cua progress

    public void progress(int bc1) {
        max = bc1;
        Thread a;
        ProgressBar.setStringPainted(true);
        a = new Thread(new Runnable() {
            @Override
            public void run() {
                if (max == 99) {
                    bc = 10;
                } else {
                    if (max == 200) {
                        bc = 2;
                        max = 100;
                    } else {
                        bc = 5;
                    }
                }
                ProgressBar.setValue(0);
                for (int i = 1; i <= max; i++) {
                    try {
                        ProgressBar.setValue(i);
                        Thread.sleep(bc);
                    } catch (InterruptedException ex) {
                    }
                }
                if (ProgressBar.getValue() == 99) {
                    loginStatus.setText("Login error ! UserName/Password is not valid !");
                }
            }
        });
        a.start();
    }

    // dinh dang thoi gian 
    public String formatDate() {
        DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        Date date = new Date();
        String strDate = dateformat.format(date);
        return strDate;
    }
    /*
     Manager Client
     */

    public void AddClient() {

        String name = CheckIn_NameClient.getText();
        int age = Integer.parseInt(Checkin_AgeClient.getText());
        String address = Checkin_Address_Client_tf.getText();
        String dateIn = Checkin_Client_Datein_tf.getText();
        String dateOut = Checkin_Client_dateout_tf.getText();
        String gender = "Female";
        if (Checkin_Male_Client_rd.isSelected()) {
            gender = "Male";
        }
        int CMND = Integer.parseInt(Ckeckin_Client_CMND_tf.getText());
        String phone = Ckeckin_Client_Phone_tf.getText();
        if (!name.equals("") && age != 0 && !address.equals("") && !dateIn.equals("") && !gender.equals("")) {
            Client c = new Client(name, age, gender, address, phone, dateIn, dateOut, CMND);
            try {
                consDB.inserClient(c);
//               JOptionPane.showConfirmDialog(this, )
            } catch (Exception ex) {
                JOptionPane.showConfirmDialog(this, " information error");
            }
        } else {
            JOptionPane.showConfirmDialog(this, " dont enought information !");
        }
    }
    /*
     Manager Staff 
     */

    //data Table
    public void StaffData(String name) {
        TbModel = new DefaultTableModel();
        TbModel.addColumn("ID");
        TbModel.addColumn("Name");
        TbModel.addColumn("Gender");
        TbModel.addColumn("Phone");
        TbModel.addColumn("Email");
        TbModel.addColumn("Office");
        this.Staff_table.setModel(TbModel);
        try {
            LoadTableStaff(name);
        } catch (Exception ex) {

        }
    }

    // load table staff
    public void LoadTableStaff(String name) throws Exception {

        TbModel.getDataVector().clear();
//        List<Staff> listStaff = consDB.getStaff(name);
        List<Staff> listStaff = constractor.getStaff(name);
        for (Iterator<Staff> it = listStaff.iterator(); it.hasNext();) {
            Staff s = it.next();
            Vector v = new Vector();
            //Staff s = new Staff(id,names,sex,phone,mail,office);
            v.addElement(s.id);
            v.addElement(s.name);
            v.addElement(s.sex);
            v.addElement(s.phone);
            v.addElement(s.email);
            v.addElement(s.office);
            TbModel.addRow(v);
        }
    }
    /* 
     Manager Room
     */
//    private List<Room> listRoom;

    public void loadTableRoom() {
        TbModel = new DefaultTableModel();

        TbModel.addColumn("No Room");
        TbModel.addColumn("Kind Of Room");
        TbModel.addColumn("Price Room");
        TbModel.addColumn("Price Current");
        TbModel.addColumn("Status Room");
//        TbModel.addColumn("Select");
        this.Checkin_Room_Table.setModel(TbModel);
        try {
            ListRoom();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, " Not Load data ");
        }
    }

    public void ListRoom() throws Exception {

        TbModel.getDataVector().clear();
        List<Room> listRoom = consDB.getListRoom();
        for (Room r : listRoom) {
            Vector v = new Vector();
            v.addElement(r.NoRoom);
            v.addElement(r.kindRoom);
            v.addElement(r.price);
            if (r.priceCurrent == 0) {
                r.priceCurrent = r.price;
            }
            v.addElement(r.priceCurrent);
            v.addElement(r.R_Status);
//            v.addElement(new Boolean(false));
            TbModel.addRow(v);
        }
    }
    //quan ly bill
    // load du lieu bill
    private ConstractorDB consDB;

//    public void BillData(String name) {
//        TbModel = new DefaultTableModel();
//        TbModel.addColumn("Stt");
//        TbModel.addColumn("Discrip");
//        TbModel.addColumn("So luong");
//        TbModel.addColumn("Don gia");
//        TbModel.addColumn("Thanh Tien");
//        this.Bill_Table.setModel(TbModel);
//        try {
//            LoadTabeBill("thuy1");
//        } catch (Exception ex) {
//            JOptionPane.showConfirmDialog(this, "Khong load dc du lieu ");
//        }
//    }
    public void LoadTabeBill(String name) throws Exception {
        TbModel.getDataVector().clear();
        int i = 1;
        List<Orders> listOrder = consDB.getOrder(name, 2);

        for (Orders o : listOrder) {
            Vector v1 = new Vector();
            v1.addElement(i);
            v1.addElement(o.noRoom);
            v1.addElement(o.id);
            v1.addElement(o.priceRoom);
            v1.addElement(o.priceService);
            TbModel.addRow(v1);
            List<OrderService> listOService = consDB.getOService(o.id);
            for (OrderService OService : listOService) {
                i++;
                Vector v = new Vector();
                v.addElement(i);
                v.addElement(OService.nameSevice);
                v.addElement(OService.quantity);
                v.addElement(OService.price);
                v.addElement(OService.price * OService.quantity);
                TbModel.addRow(v);
            }
        }
    }

    private void LoginBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtActionPerformed
        // TODO add your handling code here:

        String pass = String.valueOf(PassWord.getPassword());
        String userName = Account_tf.getText();
        try {
            if (constractor.Login(userName, pass) == 1) {
                LoginFrame.setVisible(false);
                Wellcome.setVisible(true);
                this.progress(100);
                StatusTxt.setText(userName + " : " + formatDate());
            } else if (constractor.Login(userName, pass) == 0) {
                loginStatus.setText("Ban nhap sai !");
            }
        } catch (Exception ex) {
            ConnectoDB_dialog.setVisible(true);
            ConnectoDB_dialog.setLocation(400, 200);
        }

    }//GEN-LAST:event_LoginBtActionPerformed

    private void staff_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_btActionPerformed
        // TODO add your handling code here:
        Staff_InternarFrame.setSize(100, 11);
        MainFrame.removeAll();
        MainFrame.add(Staff_InternarFrame);
        try {
            Staff_InternarFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Hotel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Staff_InternarFrame.toFront();
        try {
            StaffData(null);
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, " Error don't load data staff !");
        }
    }//GEN-LAST:event_staff_btActionPerformed

    private void Account_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Account_tfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LoginBt.doClick();
        }
    }//GEN-LAST:event_Account_tfKeyPressed

    private void PassWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassWordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LoginBt.doClick();
        }
    }//GEN-LAST:event_PassWordKeyPressed

    private void Services_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Services_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Services_tfActionPerformed

    private void Conec_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conec_btActionPerformed
        String address = IpAdress_tf.getText();
        String name = userNamedb_tf.getText();
        String port = port_tf.getText();
        String pass = String.valueOf(passDb_tf.getPassword());
        String dbName = Services_tf.getText();
        Confix con = new Confix(address, port, dbName, name, pass);
        writeFile(con);
    }//GEN-LAST:event_Conec_btActionPerformed

    private void ClearDb_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearDb_btActionPerformed
        clearForm();

    }//GEN-LAST:event_ClearDb_btActionPerformed

    private void CloseDB_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseDB_btActionPerformed
        ConnectoDB_dialog.setVisible(false);
    }//GEN-LAST:event_CloseDB_btActionPerformed

    private void staff_Reset_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_Reset_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_Reset_btActionPerformed

    private void staff_add_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_add_btActionPerformed
        //Staff s = new Staff(id,names,sex,phone,mail,office);
        String id = idStaff_tf.getText();
        String name = staffname_tf.getText();
        int phone = Integer.parseInt(Staff_phone_tf.getText());
        String mail = staff_mail_tf.getText();
        String office = staff_office_tf.getText();
        String sex = "Famel";
        if (!id.equals("") && !name.equals("") && phone != 0 && !mail.equals("") && !office.equals("")) {

            if (StaffMale_btradio.isSelected()) {
                sex = "Male";
            }
            Staff s = new Staff(id, name, sex, phone, mail, office);
            try {
                constractor.insertStaff(s);
                StaffData(null);
            } catch (Exception ex) {
                JOptionPane.showConfirmDialog(this, " Error ");
            }
        } else {
            JOptionPane.showConfirmDialog(this, " Ban chua dien du thong tin ");
        }
    }//GEN-LAST:event_staff_add_btActionPerformed

    private void Ordel_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ordel_btActionPerformed
        Staff_InternarFrame.setSize(100, 11);
        MainFrame.removeAll();
        MainFrame.add(Order_InternerFrame);
        try {
            Order_InternerFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Hotel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Order_InternerFrame.toFront();
        try {
            loadTableRoom();
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(this, " Error !");
        }

    }//GEN-LAST:event_Ordel_btActionPerformed

    private void Checkin_AgeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Checkin_AgeClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Checkin_AgeClientActionPerformed

    private void Order_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Order_listMouseClicked
        int Row = Order_list.getSelectedIndex();
        switch (Row) {
            case 1:
                // load lai table
                break;
            case 2:
                break;
            case 3:
                break;
            case 4:
                break;
            case 5:
                break;
        }
    }//GEN-LAST:event_Order_listMouseClicked

    private void Checkin_Room_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Checkin_Room_TableMouseClicked
        // check in 
        int Row = Checkin_Room_Table.getSelectedRow();

        Room r = new Room();
        r.NoRoom = (String) Checkin_Room_Table.getValueAt(Row, 0);
        r.R_Status = (String) Checkin_Room_Table.getValueAt(Row, 4);
//        insertCheckin(r);
        this.Order_Question_dialog.setVisible(true);

    }//GEN-LAST:event_Checkin_Room_TableMouseClicked

    private void Question_Yes_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question_Yes_btActionPerformed
        this.Order_Question_dialog.setVisible(false);
    }//GEN-LAST:event_Question_Yes_btActionPerformed

    private void CheckIn_insert_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckIn_insert_btActionPerformed
//        AddClient();
        int Row = Checkin_Room_Table.getSelectedRow();

        Room r = new Room();
        r.NoRoom = (String) Checkin_Room_Table.getValueAt(Row, 0);
        r.R_Status = (String) Checkin_Room_Table.getValueAt(Row, 4);
        insertCheckin(r);
    }//GEN-LAST:event_CheckIn_insert_btActionPerformed
    public void insertCheckin(Room r) {
//        int Row = Checkin_Room_Table.getSelectedRow();
//        Room r = new Room();
//        r.NoRoom = (String) Checkin_Room_Table.getValueAt(Row, 0);
//        r.R_Status = (String) Checkin_Room_Table.getValueAt(Row, 4);
        if (r.R_Status.equals("")) {
            try {

                r.R_Status = " Dang Su Dung";
                consDB.UpdateRoom(r, 5);
                loadTableRoom();
            } catch (Exception ex) {
                JOptionPane.showConfirmDialog(this, " Dont Load Data");
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Phong dang duoc su dung ! ");
        }
    }

    // writer file object
    public void writeFile(Confix con) {
        try {
            try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("confix.dat"))) {
                out.writeObject(con);
            }
            constractor = new Constractor();
            JOptionPane.showConfirmDialog(this, " Connected to database");
            ConnectoDB_dialog.setVisible(false);
//            main(new String[1]);
        } catch (IOException ex) {
            Logger.getLogger(Hotel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void clearForm() {
        IpAdress_tf.setText("");
        userNamedb_tf.setText("");
        port_tf.setText("");
        passDb_tf.setText("");
        Services_tf.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Hotel.class.getName()).log(Level.SEVERE, null, ex);
                }
                new Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Account_tf;
    private javax.swing.JTextField CheckIn_NameClient;
    private javax.swing.JButton CheckIn_insert_bt;
    private javax.swing.JPanel CheckOut;
    private javax.swing.JTextField Checkin_Address_Client_tf;
    private javax.swing.JTextField Checkin_AgeClient;
    private javax.swing.JButton Checkin_Clear_bt;
    private javax.swing.JTextField Checkin_Client_Datein_tf;
    private javax.swing.ButtonGroup Checkin_Client_Gender_btgroup;
    private javax.swing.JTextField Checkin_Client_dateout_tf;
    private javax.swing.JRadioButton Checkin_Female_Client_rd;
    private javax.swing.JRadioButton Checkin_Male_Client_rd;
    private javax.swing.JPanel Checkin_Panel;
    private javax.swing.JTable Checkin_Room_Table;
    private javax.swing.JTextField Ckeckin_Client_CMND_tf;
    private javax.swing.JTextField Ckeckin_Client_Phone_tf;
    private javax.swing.JButton Ckeckin_Update_bt;
    private javax.swing.JButton ClearDb_bt;
    private javax.swing.JButton CloseDB_bt;
    private javax.swing.JButton Conec_bt;
    private javax.swing.JDialog ConnectoDB_dialog;
    private javax.swing.JTextField IpAdress_tf;
    private javax.swing.JButton LoginBt;
    private javax.swing.JInternalFrame LoginFrame;
    private javax.swing.JDesktopPane MainFrame;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Ordel_bt;
    private javax.swing.JInternalFrame Order_InternerFrame;
    private javax.swing.JDialog Order_Question_dialog;
    private javax.swing.JList Order_list;
    private javax.swing.JPasswordField PassWord;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton Question_No_bt;
    private javax.swing.JButton Question_Yes_bt;
    private javax.swing.JButton ResetBt;
    private javax.swing.JTextField Services_tf;
    private javax.swing.JRadioButton StaffMale_btradio;
    private javax.swing.JInternalFrame Staff_InternarFrame;
    private javax.swing.JTextField Staff_phone_tf;
    private javax.swing.JTable Staff_table;
    private javax.swing.JLabel StatusTxt;
    private javax.swing.JButton Wellcome;
    private javax.swing.JTextField idStaff_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginStatus;
    private javax.swing.JPasswordField passDb_tf;
    private javax.swing.JTextField port_tf;
    private javax.swing.JRadioButton staffFemale_btradio;
    private javax.swing.ButtonGroup staffGender;
    private javax.swing.JButton staff_Reset_bt;
    private javax.swing.JButton staff_add_bt;
    private javax.swing.JButton staff_bt;
    private javax.swing.JTextField staff_mail_tf;
    private javax.swing.JTextField staff_office_tf;
    private javax.swing.JButton staff_search_bt;
    private javax.swing.JTextField staff_search_tf;
    private javax.swing.JTextField staffname_tf;
    private javax.swing.JTextField userNamedb_tf;
    // End of variables declaration//GEN-END:variables
}
